### PR TITLE
fix: cleanup homepage

### PR DESCRIPTION
**Pull request by ndom91**
Hey guys, big fan of the `nvim` setup. Looks like the site could use some major clean up though..

I've a frontend web dev during the day and have some experience running big docusaurus sites as well. Would be happy to help out further here!

Anyway, this PR did a bunch of different things, including:

- [x] Cleaning up and fixing the homepage CSS and also makes the hero screenshot keep its aspect ratio when you resize
- [x] Added to `.gitignore` the `/build` and `/.docusaurus` folders - these are both just temporary build artifact type files that get generated everytime you start/build. No need to commit these to the repo.
- [x] sidebar / navbar links and active paths now work as designed.
- [x] added a little fadeIn animation to hero screenshot
- [x] fixed some darkmode font colors - headings were dark on dark colored
- [x] the docs pages themselves were renamed to more easily work with them (lowercase and with `-`, for example). The syntax here isn't important, you can change it to whatever you like. The point is that the filename doesn't have to be the display name. That's defined separately in the markdown file in the frontmatter (configs at the top of markdown files between the `---`).  
- [x] I also added some common web dev development dependencies like prettier and set it up to run on commit via `simple-git-hooks` (a more lightweight, easier to config alternative to husky). Feel free to remove any of these dev dependencies, but I'd strongly recommend you keep them. Especially if multiple people are going to be working on this, keeping code consistent will be so much easier with this infra in place.

Check out the preview deploy from Netlify, let me know what yall think! Like I said, I'd be happy to help out further clean up / professionalise this a bit :+1:

### CODE REVIEW

**Comment by siduck76** [comment]
@ndom91 sorry for the late response! Im unable to get notifs for this repo lol , but then realized its moved to NvChad org . Feel free to join our discord server! and thanks for all your work , I will look onto it

**Comment by siduck76** [comment]
@ndom91 
image

**Comment by ndom91** [comment]
> @ndom91
> image

Good catch! Was applying homepage styles to the `container` class, without realising `container` is a general class reused all over the place. 

Fixed now :+1:

**Comment by G-Rowell** [comment]
@ndom91 

Hot damn!!!

`+7,849 −36,484 ` lol, the change in loc


Thanks so much for the contribution, awesome to have this help! :heart: 

Much appreciated!!!!!! :rocket:

**Comment by ndom91** [comment]
> @ndom91 
> 
> Hot damn!!!
> 
> `+7,849 −36,484 ` lol, the change in loc
> 
> 
> Thanks so much for the contribution, awesome to have this help! :heart: 
> 
> Much appreciated!!!!!! :rocket: 

Haha yeah primarily cause of all the build artifacts that were previously commited in the repo (`/build` and `/.docusaurus`) 😅

**Pull request merged**
